from tkinter import *
root=Tk()
root.title("online bus booking system")
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(w,h))
frame1=Frame(root)
frame1.grid(row=0,column=0,columnspan=12,padx=(200,0))
Img=PhotoImage(file='.\\Bus_for_project.png')
Label(frame1,image=Img).grid(row=0,column=0,columnspan=15)
Label(frame1,text="Online Bus Booking System",fg='red',font=("Arial bold",25),bg='light blue').grid(row=1,column=1,pady=(0,30),columnspan=12)
Label(frame1,text="Add Bus Running Detail",font=("Arial bold",15),fg='red').grid(row=2,column=1,pady=(0,30),columnspan=12)
Label(frame1,text="Bus id",font=("Arial bold",10)).grid(row=3,column=0)
Entry(frame1).grid(row=3,column=1)
Label(frame1,text="Running Date",font=("Arial bold",10)).grid(row=3,column=2,padx=5)
Entry(frame1).grid(row=3,column=3)
Label(frame1,text="Seat Available",font=("Arial bold",10)).grid(row=3,column=4,padx=10)
Entry(frame1).grid(row=3,column=5)
Button(frame1,text='Add Run',bg='pale green',font=("Arial bold",10)).grid(row=3,column=6,padx=10,pady=40)
Button(frame1,text='Delete Run',bg='pale green',font=("Arial bold",10)).grid(row=3,column=7,padx=10)
homebutton=PhotoImage(file='.\\home.png')
Label(frame1,image=homebutton).grid(row=4,column=6)
Button(frame1, image=homebutton).grid(row=4,column=6)
