from tkinter import *
root=Tk()
root.title("online bus booking system")
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(w,h))
frame1=Frame(root)
frame1.grid(row=0,column=0,columnspan=10,padx=w/3)
Img=PhotoImage(file='.\\Bus_for_project.png')
Label(frame1,image=Img).grid(row=0,column=0,columnspan=12)
Label(frame1,text="Online Bus Booking System",fg='red',font=("Arial bold",25),bg='light blue').grid(row=1,column=1,pady=(0,30),columnspan=12)
Label(frame1,text="Check Your Booking",font=("Arial bold",15),bg='pale green',fg='red').grid(row=2,column=1,pady=(0,30),columnspan=12)
Label(frame1,text="Enter Your Mobile No.",font=("Arial bold",10)).grid(row=3,column=2,rowspan=3)
Entry(frame1).grid(row=3,column=3)
Button(frame1,text='Check Booking',font=("Arial bold",10)).grid(row=3,column=4)
