from tkinter import *
root=Tk()
root.title("online bus booking system")
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(w,h))
frame1=Frame(root)
frame1.grid(row=0,column=0,columnspan=12,padx=(150,0))
Img=PhotoImage(file='.\\Bus_for_project.png')
Label(frame1,image=Img).grid(row=0,column=0,columnspan=15)
Label(frame1,text="Online Bus Booking System",fg='red',font=("Arial bold",25),bg='light blue').grid(row=1,column=1,pady=(0,30),columnspan=12)
Label(frame1,text="Add Bus Route Detail",font=("Arial bold",15),fg='red').grid(row=2,column=1,pady=(0,30),columnspan=12)
Label(frame1,text="Route ID",font=("Arial bold",10)).grid(row=3,column=0)
Entry(frame1).grid(row=3,column=1)
Label(frame1,text="Station Name",font=("Arial bold",10)).grid(row=3,column=2)
Entry(frame1).grid(row=3,column=3)
Label(frame1,text="Station ID",font=("Arial bold",10)).grid(row=3,column=4,padx=10)
Entry(frame1).grid(row=3,column=5,pady=50)
Button(frame1,text='Add Route',bg='pale green',font=("Arial bold",10)).grid(row=3,column=7,padx=20)
Button(frame1,text='Delete Route',bg='pale green',font=("Arial bold",10)).grid(row=3,column=8,padx=20)
homebutton=PhotoImage(file='.\\home.png')
Label(frame1,image=homebutton).grid(row=4,column=6)
Button(frame1, image=homebutton).grid(row=4,column=6)
